// <auto-generated />
using System;
using APIP2Minardi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIP2Minardi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("APIP2Minardi.Models.Medicamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dosagem")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Via_Administracao")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Medico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Leito")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("SETOR_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("SETOR_id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("APIP2Minardi.Models.PrescricaoGeral", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("MEDICO_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PACIENTE_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("MEDICO_id");

                    b.HasIndex("PACIENTE_id");

                    b.ToTable("PrescricoesGerais");
                });

            modelBuilder.Entity("APIP2Minardi.Models.PrescricaoMedicamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frequencia")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("MEDICAMENTO_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PRESCRICAO_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quantidade")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("MEDICAMENTO_id");

                    b.HasIndex("PRESCRICAO_id");

                    b.ToTable("PrescricoesMedicamentos");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Setor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Andar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Paciente", b =>
                {
                    b.HasOne("APIP2Minardi.Models.Setor", "Setor")
                        .WithMany("Pacientes")
                        .HasForeignKey("SETOR_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("APIP2Minardi.Models.PrescricaoGeral", b =>
                {
                    b.HasOne("APIP2Minardi.Models.Medico", "Medico")
                        .WithMany("PrescricaosGerais")
                        .HasForeignKey("MEDICO_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIP2Minardi.Models.Paciente", "Paciente")
                        .WithMany("PrescricoesGerais")
                        .HasForeignKey("PACIENTE_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("APIP2Minardi.Models.PrescricaoMedicamento", b =>
                {
                    b.HasOne("APIP2Minardi.Models.Medicamento", "Medicamentos")
                        .WithMany("PrecricaoMedicamentos")
                        .HasForeignKey("MEDICAMENTO_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIP2Minardi.Models.PrescricaoGeral", "PrescricaoGeral")
                        .WithMany("PrecricaoMedicamentos")
                        .HasForeignKey("PRESCRICAO_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamentos");

                    b.Navigation("PrescricaoGeral");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Medicamento", b =>
                {
                    b.Navigation("PrecricaoMedicamentos");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Medico", b =>
                {
                    b.Navigation("PrescricaosGerais");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Paciente", b =>
                {
                    b.Navigation("PrescricoesGerais");
                });

            modelBuilder.Entity("APIP2Minardi.Models.PrescricaoGeral", b =>
                {
                    b.Navigation("PrecricaoMedicamentos");
                });

            modelBuilder.Entity("APIP2Minardi.Models.Setor", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
